/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange username/password for an access + refresh token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke a refresh token (idempotent — always returns 204).
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently authenticated user.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Patch the current user's profile. Only non-``None`` fields are applied.
         *
         *     A username change is guarded against collision with another account.
         */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate a refresh token: revoke the old one, issue a new pair.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runtime Config
         * @description Return the current model, version, and where the model name came from.
         *
         *     The frontend terminal footer reads this to display ``MODEL <name>``.
         *     We prefer the live vLLM ``/v1/models`` response (source-of-truth for what's
         *     actually loaded), and fall back to the configured env value if vLLM is
         *     unreachable so the bar never breaks.
         */
        get: operations["get_runtime_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Servers
         * @description List the current user's MCP servers, oldest first (insertion order).
         */
        get: operations["list_servers_v1_mcp_servers_get"];
        put?: never;
        /**
         * Create Server
         * @description Register a new MCP server. ``auth_token`` (if provided) is Fernet-encrypted
         *     before persisting and never echoed back.
         */
        post: operations["create_server_v1_mcp_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mcp/servers/{server_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Server */
        get: operations["get_server_v1_mcp_servers__server_id__get"];
        put?: never;
        post?: never;
        /** Delete Server */
        delete: operations["delete_server_v1_mcp_servers__server_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Server
         * @description Partial update. ``auth_token`` semantics: omit to leave the existing
         *     cipher in place; pass empty string to clear; pass any non-empty value
         *     to replace.
         */
        patch: operations["update_server_v1_mcp_servers__server_id__patch"];
        trace?: never;
    };
    "/v1/mcp/servers/{server_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Server */
        post: operations["sync_server_v1_mcp_servers__server_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Personas
         * @description List the current user's personas + any built-ins.
         */
        get: operations["list_personas_v1_personas_get"];
        put?: never;
        /**
         * Create Persona
         * @description Create a persona owned by the current user.
         */
        post: operations["create_persona_v1_personas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Persona
         * @description Fetch one persona (owned by the user or a built-in).
         */
        get: operations["get_persona_v1_personas__persona_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Persona
         * @description Delete one of the user's personas. Built-ins can't be removed.
         */
        delete: operations["delete_persona_v1_personas__persona_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Persona
         * @description Patch a persona. Built-ins are read-only — 403 on edit.
         */
        patch: operations["update_persona_v1_personas__persona_id__patch"];
        trace?: never;
    };
    "/v1/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pins
         * @description List the user's pinned messages, ordered by ``position`` then creation.
         */
        get: operations["list_pins_v1_pins_get"];
        put?: never;
        /**
         * Create Pin
         * @description Pin a message. 404 if the message belongs to another user's session,
         *     409 if already pinned.
         */
        post: operations["create_pin_v1_pins_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pins/{pin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Pin
         * @description Unpin a message. 404 if the pin doesn't belong to the caller.
         */
        delete: operations["delete_pin_v1_pins__pin_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Pin
         * @description Patch the pin's title and/or position.
         */
        patch: operations["update_pin_v1_pins__pin_id__patch"];
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List the current user's sessions, newest first.
         */
        get: operations["list_sessions_v1_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new empty session.
         */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Return a session and all its messages.
         */
        get: operations["get_session_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a session and all its messages.
         */
        delete: operations["delete_session_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Session
         * @description Update a session (title / archived / persona).
         */
        patch: operations["update_session_v1_sessions__session_id__patch"];
        trace?: never;
    };
    "/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description Return the messages of a session, with tool results merged in.
         */
        get: operations["list_messages_v1_sessions__session_id__messages_get"];
        put?: never;
        /**
         * Post Message
         * @description Post a user message and stream the assistant response as SSE.
         */
        post: operations["post_message_v1_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tools
         * @description List every available tool with its ``enabled`` state for the current user.
         */
        get: operations["list_tools_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle Tool
         * @description Enable or disable a tool for the current user.
         */
        put: operations["toggle_tool_v1_tools__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HyperParams
         * @description Partial sampling-parameter map. Every field may be absent.
         */
        HyperParams: {
            /** Enable Thinking */
            enable_thinking?: boolean | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Min P */
            min_p?: number | null;
            /** Presence Penalty */
            presence_penalty?: number | null;
            /** Repetition Penalty */
            repetition_penalty?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Top K */
            top_k?: number | null;
            /** Top P */
            top_p?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * MCPServerCreate
         * @description Body for ``POST /v1/mcp/servers``. ``auth_token`` is the raw bearer
         *     token typed by the user; the API endpoint encrypts it at rest before
         *     persisting.
         */
        MCPServerCreate: {
            /** Auth Token */
            auth_token?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Name */
            name: string;
            /**
             * Transport
             * @default http
             * @constant
             */
            transport: "http";
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /**
         * MCPServerPublic
         * @description Read shape — never includes the auth token. ``has_auth_token`` is a
         *     boolean hint so the frontend can show 'token configured' vs an empty
         *     field without ever surfacing the secret.
         */
        MCPServerPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Has Auth Token */
            has_auth_token: boolean;
            /** Id */
            id: number;
            /** Last Sync Error */
            last_sync_error: string | null;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Name */
            name: string;
            /** Synced Tools */
            synced_tools?: components["schemas"]["MCPToolInfo"][];
            /**
             * Transport
             * @constant
             */
            transport: "http";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string;
        };
        /**
         * MCPServerUpdate
         * @description Partial update. Each field is optional; only present keys are
         *     applied. Pass ``auth_token: ""`` to clear the stored token, omit it to
         *     leave the existing token in place.
         */
        MCPServerUpdate: {
            /** Auth Token */
            auth_token?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Name */
            name?: string | null;
            /** Transport */
            transport?: "http" | null;
            /** Url */
            url?: string | null;
        };
        /**
         * MCPSyncResult
         * @description Returned by ``POST /v1/mcp/servers/{id}/sync``. Mirrors what gets
         *     persisted on the row plus a friendly count for the toast.
         */
        MCPSyncResult: {
            server: components["schemas"]["MCPServerPublic"];
            /** Tools Count */
            tools_count: number;
        };
        /**
         * MCPToolInfo
         * @description Snapshot of one tool advertised by an MCP server, persisted in
         *     ``mcp_servers.synced_tools`` so chat completions don't pay the
         *     round-trip on every send.
         */
        MCPToolInfo: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Parameters Schema */
            parameters_schema?: {
                [key: string]: unknown;
            };
        };
        /** MessageCreate */
        MessageCreate: {
            /** Content */
            content: string;
        };
        /** MessagePublic */
        MessagePublic: {
            /** Content */
            content: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Reasoning */
            reasoning: string | null;
            /** Role */
            role: string;
            /** Tool Call Id */
            tool_call_id: string | null;
            /** Tool Calls */
            tool_calls: {
                [key: string]: unknown;
            }[] | null;
        };
        /** PersonaCreate */
        PersonaCreate: {
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** System Prompt */
            system_prompt: string;
        };
        /** PersonaPublic */
        PersonaPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Builtin */
            is_builtin: boolean;
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** System Prompt */
            system_prompt: string;
        };
        /**
         * PersonaUpdate
         * @description Partial update — only non-``None`` fields are applied.
         */
        PersonaUpdate: {
            /** Name */
            name?: string | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
            /** System Prompt */
            system_prompt?: string | null;
        };
        /**
         * PinCreate
         * @description Body for ``POST /v1/pins``.
         */
        PinCreate: {
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Title */
            title: string;
        };
        /**
         * PinPublic
         * @description Serialised pin as returned by the API.
         *
         *     Carries enough denormalised message context (``session_id``, an
         *     excerpt, role) so the home dashboard can render the card without a
         *     second request per pin.
         */
        PinPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Excerpt */
            excerpt: string;
            /** Id */
            id: number;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Position */
            position: number;
            /** Role */
            role: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Title */
            title: string;
        };
        /**
         * PinUpdate
         * @description Body for ``PATCH /v1/pins/{id}`` — partial update.
         */
        PinUpdate: {
            /** Position */
            position?: number | null;
            /** Title */
            title?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * RuntimeConfig
         * @description What the UI status bar needs to render the ambient chrome.
         */
        RuntimeConfig: {
            /** Model */
            model: string;
            /** Model Source */
            model_source: string;
            /** Version */
            version: string;
        };
        /** SessionCreate */
        SessionCreate: {
            /** Model */
            model?: string | null;
            overrides?: components["schemas"]["HyperParams"];
            /** Persona Id */
            persona_id?: number | null;
            /**
             * Title
             * @default New conversation
             */
            title: string;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Messages */
            messages?: components["schemas"]["MessagePublic"][];
            /** Model */
            model: string | null;
            overrides?: components["schemas"]["HyperParams"];
            /** Persona Id */
            persona_id: number | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionPublic */
        SessionPublic: {
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model */
            model: string | null;
            overrides?: components["schemas"]["HyperParams"];
            /** Persona Id */
            persona_id: number | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SessionUpdate */
        SessionUpdate: {
            /** Archived */
            archived?: boolean | null;
            /** Model */
            model?: string | null;
            overrides?: components["schemas"]["HyperParams"] | null;
            /** Persona Id */
            persona_id?: number | null;
            /** Title */
            title?: string | null;
        };
        /** TokenPair */
        TokenPair: {
            /**
             * Access Expires At
             * Format: date-time
             */
            access_expires_at: string;
            /** Access Token */
            access_token: string;
            /**
             * Refresh Expires At
             * Format: date-time
             */
            refresh_expires_at: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ToolInfo */
        ToolInfo: {
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
            /** Icon */
            icon: string | null;
            /** Name */
            name: string;
            /** Title */
            title: string;
        };
        /** ToolToggle */
        ToolToggle: {
            /** Enabled */
            enabled: boolean;
        };
        /** UserPublic */
        UserPublic: {
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Persona Id */
            default_persona_id?: number | null;
            defaults?: components["schemas"]["HyperParams"];
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /** Locality */
            locality?: string | null;
            /**
             * Temperature Unit
             * @default C
             * @enum {string}
             */
            temperature_unit: "C" | "F";
            /**
             * Time Format
             * @default 24h
             * @enum {string}
             */
            time_format: "12h" | "24h";
            /** Username */
            username: string;
        };
        /**
         * UserUpdate
         * @description Partial profile update. All fields optional; only non-``None`` values
         *     are applied. ``username`` goes through the same uniqueness check as
         *     registration. ``default_persona_id`` supports explicit ``null`` to detach
         *     — "unset" vs "set to None" is distinguished via ``model_fields_set``.
         */
        UserUpdate: {
            /** Avatar Url */
            avatar_url?: string | null;
            /** Default Persona Id */
            default_persona_id?: number | null;
            defaults?: components["schemas"]["HyperParams"] | null;
            /** Locality */
            locality?: string | null;
            /** Temperature Unit */
            temperature_unit?: ("C" | "F") | null;
            /** Time Format */
            time_format?: ("12h" | "24h") | null;
            /** Username */
            username?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_runtime_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    list_servers_v1_mcp_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServerPublic"][];
                };
            };
        };
    };
    create_server_v1_mcp_servers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MCPServerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_v1_mcp_servers__server_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_server_v1_mcp_servers__server_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_server_v1_mcp_servers__server_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MCPServerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPServerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_server_v1_mcp_servers__server_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPSyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_v1_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaPublic"][];
                };
            };
        };
    };
    create_persona_v1_personas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_persona_v1_personas__persona_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_persona_v1_personas__persona_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_persona_v1_personas__persona_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pins_v1_pins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinPublic"][];
                };
            };
        };
    };
    create_pin_v1_pins_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pin_v1_pins__pin_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pin_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pin_v1_pins__pin_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pin_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_sessions_get: {
        parameters: {
            query?: {
                archived?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_v1_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_v1_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_v1_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"][];
                };
            };
        };
    };
    toggle_tool_v1_tools__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolToggle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
